### ISSUE TITLE
修复开发环境下CSS文件返回404的问题

### ISSUE THREAD

**Issue by zhongzhi107** [packingjs/packing#10]
因为开发环境未输出CSS实体文件，但模版中却写了对css文件的引用，所有开发预览时css会返回404

**Comment by zhongzhi107** [comment]
@LHoin

**Comment by jaylone** [comment]
👍

**Comment by zhongzhi107** [comment]
#12 

用法请参考：
https://github.com/LHoin/webpack-uncomment-block
