### ISSUE TITLE
页面代码变更也会影响到vendor.js版本号

### ISSUE THREAD

**Issue by jaylone** [packingjs/packing#14]
只变更业务代码，vendor.js的版本号也会变化
[http://www.cnblogs.com/myqianlan/p/5626505.html](url)

**Comment by zhongzhi107** [comment]
https://github.com/webpack/webpack/issues/5856

https://webpack.js.org/concepts/manifest/

**Comment by zhongzhi107** [comment]
packing@2.5.2

在默认配置中增加了manifest.js，编译时比之前的版本会多输出一个manifest.js，需要在页面增加对该js文件的引用，引用的先后顺序如下：
`
<script src="vendor.js"></script>
<script src="manifest.js"></script>
<script src="页面.js"></script>
`

**Comment by jaylone** [comment]
👌，thx~
