### ISSUE TITLE
warning ... : we recommend using babel-preset-env now: 

### ISSUE THREAD

**Issue by shallinta** [packingjs/packing#15]
安装依赖包时提示：
> warning packing > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

`babel-preset-env`代码已经合并到`babel`工程的`babel/experimental/babel-preset-env/`目录。

``` sh
npm install babel-preset-env --save-dev
```

---

可以使用的配置：
``` json
{
  "presets": [
    [
      "env", {
        "useBuiltIns": "entry",
        "modules": false,
        "targets": {
          "browsers": ["> 1%", "Android >= 4.4", "IOS >= 7", "ie >= 9"],
          "node": "4.0"
        }
      }
    ]
  ],

  "plugins": []
}

```

**Comment by venoral** [comment]
I agree ...

**Comment by zhongzhi107** [comment]
Fixed.
https://github.com/packingjs/packing/commit/8edb8db8a4dccc9a9d748a5ada8145d2f0e32d24

packing@2.5.2
