### ISSUE TITLE
发dev机后，纯数字md5文件访问404

### ISSUE THREAD

**Issue by ysyfff** [packingjs/packing#16]
受到dev机Nginx中rewrite规则的限制，会将纯数字md5值rewrite为dev字符串，从而导致页面访问404

**Comment by zhongzhi107** [comment]
有个恶心的 Nginx 正则，会导致纯数字的 hash 访问时404
`
location ~ /dev/ {
  rewrite ^(.*?)-(\d+[\d.])\.(js|css)$ $1-dev.$3 last;
}
｀
