### ISSUE TITLE
postcss.config.js 配置 cssnano

### ISSUE THREAD

**Issue by shallinta** [packingjs/packing#34]
`Error: Loading PostCSS Plugin failed: Cannot find module 'nano'`

好像要配置成
```js
{
  cssnano: {}
}
```

**Comment by zhongzhi107** [comment]
看起来是缺少 nano 依赖包

**Comment by shallinta** [comment]
我搜了一下，没有nano或者postcss-nano的包呀。我看你的package.json里装的也是cssnano

**Comment by zhongzhi107** [comment]
不能复现，请使用最新的packing版本
